-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS "DarkSouls".enemies
(
    enemy_id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    enemy_name text COLLATE pg_catalog."default" NOT NULL,
    enemy_type text COLLATE pg_catalog."default" NOT NULL,
    item_id smallint,
    CONSTRAINT enemies_pkey PRIMARY KEY (enemy_id)
);

CREATE TABLE IF NOT EXISTS "DarkSouls".enemies_locations
(
    enemy_id smallint,
    location_id smallint
);

CREATE TABLE IF NOT EXISTS "DarkSouls".items
(
    item_id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    item_name text COLLATE pg_catalog."default" NOT NULL DEFAULT 'unknown'::text,
    item_description text COLLATE pg_catalog."default" NOT NULL DEFAULT 'unknown'::text,
    item_type text COLLATE pg_catalog."default" NOT NULL DEFAULT 'unknown'::text,
    CONSTRAINT items_pkey PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS "DarkSouls".items_locations
(
    item_id smallint,
    location_id smallint
);

CREATE TABLE IF NOT EXISTS "DarkSouls".locations
(
    location_id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    location_name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT locations_pkey PRIMARY KEY (location_id)
);

CREATE TABLE IF NOT EXISTS "DarkSouls".npc
(
    npc_id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    npc_name text COLLATE pg_catalog."default" NOT NULL,
    npc_type text COLLATE pg_catalog."default" NOT NULL,
    item_id smallint,
    CONSTRAINT npc_pkey PRIMARY KEY (npc_id)
);

CREATE TABLE IF NOT EXISTS "DarkSouls".npcs_locations
(
    npc_id smallint,
    location_id smallint
);

ALTER TABLE IF EXISTS "DarkSouls".enemies
    ADD CONSTRAINT fk_enemies_item_id FOREIGN KEY (item_id)
    REFERENCES "DarkSouls".items (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "DarkSouls".enemies_locations
    ADD CONSTRAINT fk_enemy_id FOREIGN KEY (enemy_id)
    REFERENCES "DarkSouls".enemies (enemy_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "DarkSouls".enemies_locations
    ADD CONSTRAINT fk_location_id FOREIGN KEY (location_id)
    REFERENCES "DarkSouls".locations (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "DarkSouls".items_locations
    ADD CONSTRAINT fk_item_id FOREIGN KEY (item_id)
    REFERENCES "DarkSouls".items (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "DarkSouls".items_locations
    ADD CONSTRAINT fk_location_id FOREIGN KEY (location_id)
    REFERENCES "DarkSouls".locations (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "DarkSouls".npc
    ADD CONSTRAINT fk_npc_item_id FOREIGN KEY (item_id)
    REFERENCES "DarkSouls".items (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "DarkSouls".npcs_locations
    ADD CONSTRAINT fk_location_id FOREIGN KEY (location_id)
    REFERENCES "DarkSouls".locations (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "DarkSouls".npcs_locations
    ADD CONSTRAINT fk_npc_id FOREIGN KEY (npc_id)
    REFERENCES "DarkSouls".npc (npc_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;